### ISSUE TITLE
model checkpoint

### ISSUE THREAD

**Issue by wshi8** [deepwise-code/DLIA#12]
Hello,

would you please upload the model checkpoint that can be used for testing?

Best
Wendy

**Comment by deepwise-code** [comment]
sorry for no checkpoint stored now        
            
                
                    
                            
                                
                            
                            
                                wanghao
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        ---- Replied Message ***@***.***>Date10/08/2021 01:03 ***@***.***> ***@***.***>Subject[deepwise-code/DLIA] model checkpoint (#12)
Hello,
would you please upload the model checkpoint that can be used for testing?
Best
Wendy

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/deepwise-code/DLIA/issues/12",
"url": "https://github.com/deepwise-code/DLIA/issues/12",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
