### ISSUE TITLE
get my lesion_bbox.txt

### ISSUE THREAD

**Issue by Hansmsy** [deepwise-code/DLIA#13]
If I have the mask how can I get my lesion_bbox.txt?

**Comment by deepwise-code** [comment]
suggest use skimage.measure module(pip install scikit-image), it provides label and regionprops function to get connective 3d lesion region information, eg. bbox, voxels. here we give example code to extract lsion bbox info in one groudtruth mask
inst_mask = measure.label(mask, connectivity=2)
inst_props = measure.regionprops(inst_mask)
for prop in inst_props:
    x0, y0, z0, x1, y1, z1 = prop.bbox
    w, h, d = x1-x0, y1-y0, z1-z0
...

relative issue link may be help for you: https://github.com/deepwise-code/DLIA/issues/1 


------------------------------------------------------------------
发件人：Hansmsy ***@***.***>
发送时间：2021年11月16日(星期二) 19:52
收件人：deepwise-code/DLIA ***@***.***>
抄　送：Subscribed ***@***.***>
主　题：[deepwise-code/DLIA] get my lesion_bbox.txt (Issue #13)

If I have the mask how can I get my lesion_bbox.txt?
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hansmsy** [comment]
This is really a wonderful way!!!
I succeeded in getting my lesion_bbox.txt.
Thank you for helping me a lot!
